### ISSUE TITLE
shutdown times longer than 49 minutes cannot be set

### ISSUE THREAD

**Issue by nebomuk** [hakaishi/shutdown-qapps#5]

**Comment by nebomuk** [comment]
there seems to be more issues, now it always resets the counter to zero when more than 40 minutes are selected. This problem appears on different linux machines with version 1.7.09 and 1.7.1

**Comment by hakaishi** [comment]
The problem was using QDate / QTime and QDateTime. QDateTime uses a localized time and QDate and QTime not necessarily.
Also, after midnight the problems vanished, that's why I do think, that it was a problem regarding localization. The problem was caused by "if(myDate.daysTo(futureDateTime.date()) < 0)". For some reason its value was smaller than zero and then executed the body of this if-loop, in other words calling reset().
It should be tested once more today if the problem still persists, but it shouldn't. The only other reason, why the value could be smaller than zero, would be a null-pointer. But both variables are initialized.

**Comment by nebomuk** [comment]
checkinstall fails due to some package version error

**Comment by nebomuk** [comment]
dpkg-deb: error: parsing file '/var/tmp/tmp.ZskKWVfkXX/package/DEBIAN/control' near line 7 package 'shutdown':
 error in Version string 'qapps-1': version number does not start with digit

**Comment by nebomuk** [comment]
i cannot longer reproduce this bug, but i'm still using 1.7.0

**Comment by hakaishi** [comment]
Out of date
